module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/J9ZOfMMCTzSLMKkpj0rdOz',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/5hrtK2Lv/20251009-062614.jpg',
    NEWSLETTER_JID: '120363408401969787@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ǫᴀᴅᴇᴇʀ-ᴀɪ-ᴍɪɴɪ',
    OWNER_NAME: 'ǫᴀᴅᴇᴇʀ ᴋʜᴀɴ',
    OWNER_NUMBER: '923151105391',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ǫᴀᴅᴇᴇʀ ᴋʜᴀɴ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb7lx2gEquiMB6IE550l',
};
